In [34]:
# Імпортовано бібліотеки

In [50]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [ ]:
# Зчитано таблицю кількості прибулих в Україну в 2021 році для подальших групувань

In [35]:
arrivals = pd.read_excel('C:\\Users\\User\\Desktop\\PET_project\\Кількість_прибулих_2021.xlsx')

In [36]:
print(arrivals)

       Стать                Вік   2021
0      Жінки        10-14 років  10348
1   Чоловіки        45-49 років  10611
2   Чоловіки        10-14 років  10857
3      Жінки        45-49 років  11037
4   Чоловіки         80-84 роки   1255
5      Жінки          5-9 років  12803
6   Чоловіки        75-79 років   1298
7   Чоловіки          5-9 років  13427
8   Чоловіки         40-44 роки  13651
9      Жінки         40-44 роки  14510
10     Жінки           0-4 роки  15679
11  Чоловіки           0-4 роки  16605
12  Чоловіки        35-39 років  17113
13     Жінки  85 років і старші   1761
14  Чоловіки         30-34 роки  19183
15  Чоловіки        25-29 років  20248
16     Жінки        35-39 років  22806
17     Жінки        75-79 років   2838
18     Жінки         30-34 роки  28387
19     Жінки        25-29 років  28498
20  Чоловіки         20-24 роки  29965
21  Чоловіки         70-74 роки   3008
22  Чоловіки        15-19 років  30254
23     Жінки        15-19 років  33141
24     Жінки         80-84 роки   3480
25     Жінки         20-24 роки  36017
26  Чоловіки        65-69 років   4891
27  Чоловіки  85 років і старші    511
28     Жінки         70-74 роки   5326
29     Жінки        65-69 років   6912
30  Чоловіки        55-59 років   7160
31  Чоловіки         60-64 роки   7986
32  Чоловіки         50-54 роки   8142
33     Жінки         50-54 роки   8873
34     Жінки        55-59 років   9100
35     Жінки         60-64 роки   9244

In [ ]:
# Згруповано дані за віком з просумуванням значень в стовпці "2021", індекс скинуто для отримання нового DataFrame з рещультатами

In [37]:
grouped_arrivals = arrivals.groupby('Вік')['2021'].sum().reset_index()

In [ ]:
# Дані відсортовано за спаданням по значенню в стовпці "2021"

In [38]:
grouped_arrivals_sort = grouped_arrivals.sort_values (by = '2021', ascending = False)

In [39]:
print(grouped_arrivals_sort)

                  Вік   2021
3          20-24 роки  65982
2         15-19 років  63395
4         25-29 років  48746
5          30-34 роки  47570
6         35-39 років  39919
0            0-4 роки  32284
7          40-44 роки  28161
9           5-9 років  26230
8         45-49 років  21648
1         10-14 років  21205
12         60-64 роки  17230
10         50-54 роки  17015
11        55-59 років  16260
13        65-69 років  11803
14         70-74 роки   8334
16         80-84 роки   4735
15        75-79 років   4136
17  85 років і старші   2272

In [ ]:
# Збережено таблицю в форматі xlsx

In [40]:
grouped_arrivals_sort.to_excel('Кількість прибулих в 2021.xlsx', index = False)

In [ ]:
# Обчислено загальну кількість прибулих за статтю у 2021 році

In [41]:
total_arrivals = arrivals.groupby('Стать')['2021'].sum()

In [42]:
print(total_arrivals)

Стать
Жінки       260760
Чоловіки    216165
Name: 2021, dtype: int64

In [ ]:
# Розраховано загальний коефіцієнт міграції для прибулих

In [69]:
migration_ratio_arrivals = round(total_arrivals ['Чоловіки']/total_arrivals ['Жінки'], 2)

In [70]:
print(f"Коефіцієнт міграції для прибулих:{migration_ratio_arrivals}")

Коефіцієнт міграції для прибулих:0.83

In [ ]:
# Створено список, який містить кортежі з трьома елементами - стать, вікова група та кількість осіб у відповідній категорії.

In [51]:
data = [("Жінки", "10-14 років", 10348),
        ("Чоловіки", "45-49 років", 10611),
        ("Чоловіки", "10-14 років", 10857),
        ("Жінки", "45-49 років", 11037),
        ("Чоловіки", "80-84 роки", 1255),
        ("Жінки", "5-9 років", 12803),
        ("Чоловіки", "75-79 років", 1298),
        ("Чоловіки", "5-9 років", 13427),
        ("Чоловіки", "40-44 роки", 13651),
        ("Жінки", "40-44 роки", 14510),
        ("Жінки", "0-4 роки", 15679),
        ("Чоловіки", "0-4 роки", 16605),
        ("Чоловіки", "35-39 років", 17113),
        ("Жінки", "85 років і старші", 1761),
        ("Чоловіки", "30-34 роки", 19183),
        ("Чоловіки", "25-29 років", 20248),
        ("Жінки", "35-39 років", 22806),
        ("Жінки", "75-79 років", 2838),
        ("Жінки", "30-34 роки", 28387),
        ("Жінки", "25-29 років", 28498),
        ("Чоловіки", "20-24 роки", 29965),
        ("Чоловіки", "70-74 роки", 3008),
        ("Чоловіки", "15-19 років", 30254),
        ("Жінки", "15-19 років", 33141),
        ("Жінки", "80-84 роки", 3480),
        ("Жінки", "20-24 роки", 36017),
        ("Чоловіки", "65-69 років", 4891),
        ("Чоловіки", "85 років і старші", 511),
        ("Жінки", "70-74 роки", 5326),
        ("Жінки", "65-69 років", 6912),
        ("Чоловіки", "55-59 років", 7160),
        ("Чоловіки", "60-64 роки", 7986),
        ("Чоловіки", "50-54 роки", 8142),
        ("Жінки", "50-54 роки", 8873),
        ("Жінки", "55-59 років", 9100),
        ("Жінки", "60-64 роки", 9244)]

In [ ]:
# Створено словник для зберігання даних

In [52]:
age_groups = {}

In [ ]:
# Заповнено словник

In [53]:
for gender, age_group, count in data:
    if age_group not in age_groups:
        age_groups[age_group] = {"Чоловіки": 0, "Жінки": 0}
    age_groups[age_group][gender] += count

In [ ]:
# Обчислено і виведено коефіцієнти

In [54]:
for age_group, counts in age_groups.items():
    if counts["Жінки"] > 0:
        ratio = counts["Чоловіки"] / counts["Жінки"]
        print(f"Вікова категорія {age_group}: коефіцієнт = {ratio:.2f}")
    else:
        print(f"Вікова категорія {age_group}: недостатньо даних про жінок")

Вікова категорія 10-14 років: коефіцієнт = 1.05
Вікова категорія 45-49 років: коефіцієнт = 0.96
Вікова категорія 80-84 роки: коефіцієнт = 0.36
Вікова категорія 5-9 років: коефіцієнт = 1.05
Вікова категорія 75-79 років: коефіцієнт = 0.46
Вікова категорія 40-44 роки: коефіцієнт = 0.94
Вікова категорія 0-4 роки: коефіцієнт = 1.06
Вікова категорія 35-39 років: коефіцієнт = 0.75
Вікова категорія 85 років і старші: коефіцієнт = 0.29
Вікова категорія 30-34 роки: коефіцієнт = 0.68
Вікова категорія 25-29 років: коефіцієнт = 0.71
Вікова категорія 20-24 роки: коефіцієнт = 0.83
Вікова категорія 70-74 роки: коефіцієнт = 0.56
Вікова категорія 15-19 років: коефіцієнт = 0.91
Вікова категорія 65-69 років: коефіцієнт = 0.71
Вікова категорія 55-59 років: коефіцієнт = 0.79
Вікова категорія 60-64 роки: коефіцієнт = 0.86
Вікова категорія 50-54 роки: коефіцієнт = 0.92

In [ ]:
# Нижче виконано аналогічні дії з таблицею вибудих з України в 2021 році

In [55]:
left = pd.read_excel('C:\\Users\\User\\Desktop\\PET_project\\Кількість_вибулих_2021.xlsx')

In [56]:
print(left)

       Стать                Вік   2021
0   Чоловіки        45-49 років  10030
1      Жінки        10-14 років  10302
2   Чоловіки        10-14 років  10845
3      Жінки        45-49 років  10959
4      Жінки          5-9 років  12723
5   Чоловіки         80-84 роки   1273
6   Чоловіки         40-44 роки  12888
7   Чоловіки        75-79 років   1312
8   Чоловіки          5-9 років  13362
9      Жінки         40-44 роки  14424
10     Жінки           0-4 роки  14788
11  Чоловіки           0-4 роки  15548
12  Чоловіки        35-39 років  15879
13  Чоловіки         30-34 роки  17246
14     Жінки  85 років і старші   1765
15  Чоловіки        25-29 років  18110
16     Жінки        35-39 років  22722
17  Чоловіки        15-19 років  26379
18  Чоловіки         20-24 роки  27249
19     Жінки        25-29 років  28028
20     Жінки         30-34 роки  28128
21     Жінки        75-79 років   2882
22  Чоловіки         70-74 роки   2963
23     Жінки        15-19 років  30959
24     Жінки         20-24 роки  34902
25     Жінки         80-84 роки   3544
26  Чоловіки        65-69 років   4768
27  Чоловіки  85 років і старші    508
28     Жінки         70-74 роки   5342
29  Чоловіки        55-59 років   6816
30     Жінки        65-69 років   6892
31  Чоловіки         60-64 роки   7691
32  Чоловіки         50-54 роки   7776
33     Жінки         50-54 роки   8695
34     Жінки        55-59 років   8859
35     Жінки         60-64 роки   9107

In [57]:
grouped_left = left.groupby('Вік')['2021'].sum().reset_index()

In [58]:
grouped_left_sort = grouped_left.sort_values (by = '2021', ascending = False)

In [59]:
print(grouped_left_sort)

                  Вік   2021
3          20-24 роки  62151
2         15-19 років  57338
4         25-29 років  46138
5          30-34 роки  45374
6         35-39 років  38601
0            0-4 роки  30336
7          40-44 роки  27312
9           5-9 років  26085
1         10-14 років  21147
8         45-49 років  20989
12         60-64 роки  16798
10         50-54 роки  16471
11        55-59 років  15675
13        65-69 років  11660
14         70-74 роки   8305
16         80-84 роки   4817
15        75-79 років   4194
17  85 років і старші   2273

In [60]:
grouped_left_sort.to_excel('Кількість вибулих в 2021.xlsx', index = False)

In [61]:
total_left = left.groupby('Стать')['2021'].sum()

In [63]:
print(total_left)

Стать
Жінки       255021
Чоловіки    200643
Name: 2021, dtype: int64

In [71]:
migration_ratio_left = round(total_left ['Чоловіки']/total_left ['Жінки'], 2)

In [72]:
print(f"Коефіцієнт міграції для вибулих:{migration_ratio_left}")

Коефіцієнт міграції для вибулих:0.79

In [ ]:
data = [("Чоловіки", "45-49 років", 10030),
        ("Жінки", "10-14 років", 10302),
        ("Чоловіки", "10-14 років", 10845),
        ("Жінки", "45-49 років", 10959),
        ("Жінки", "5-9 років", 12723),
        ("Чоловіки", "80-84 роки", 1273),
        ("Чоловіки", "40-44 роки", 12888),
        ("Чоловіки", "75-79 років", 1312),
        ("Чоловіки", "5-9 років", 13362),
        ("Жінки", "40-44 роки", 14424),
        ("Жінки", "0-4 роки", 14788),
        ("Чоловіки", "0-4 роки", 15548),
        ("Чоловіки", "35-39 років", 15879),
        ("Чоловіки", "30-34 роки", 17246),
        ("Жінки", "85 років і старші", 1765),
        ("Чоловіки", "25-29 років", 18110),
        ("Жінки", "35-39 років", 22722),
        ("Чоловіки", "15-19 років", 26379),
        ("Чоловіки", "20-24 роки", 27249),
        ("Жінки", "25-29 років", 28028),
        ("Жінки", "30-34 роки", 28128),
        ("Жінки", "75-79 років", 2882),
        ("Чоловіки", "70-74 роки", 2963),
        ("Жінки", "15-19 років", 30959),
        ("Жінки", "20-24 роки", 34902),
        ("Жінки", "80-84 роки", 3544),
        ("Чоловіки", "65-69 років", 4768),
        ("Чоловіки", "85 років і старші", 508),
        ("Жінки", "70-74 роки", 5342),
        ("Чоловіки", "55-59 років", 6816),
        ("Жінки", "65-69 років", 6892),
        ("Чоловіки", "60-64 роки", 7691),
        ("Чоловіки", "50-54 роки", 7776),
        ("Жінки", "50-54 роки", 8695),
        ("Жінки", "55-59 років", 8859),
        ("Жінки", "60-64 роки", 9107)]

In [66]:
age_groups = {}

In [67]:
for gender, age_group, count in data:
    if age_group not in age_groups:
        age_groups[age_group] = {"Чоловіки": 0, "Жінки": 0}
    age_groups[age_group][gender] += count

In [68]:
for age_group, counts in age_groups.items():
    if counts["Жінки"] > 0:
        ratio = counts["Чоловіки"] / counts["Жінки"]
        print(f"Вікова категорія {age_group}: коефіцієнт = {ratio:.2f}")
    else:
        print(f"Вікова категорія {age_group}: недостатньо даних про жінок")

Вікова категорія 10-14 років: коефіцієнт = 1.05
Вікова категорія 45-49 років: коефіцієнт = 0.96
Вікова категорія 80-84 роки: коефіцієнт = 0.36
Вікова категорія 5-9 років: коефіцієнт = 1.05
Вікова категорія 75-79 років: коефіцієнт = 0.46
Вікова категорія 40-44 роки: коефіцієнт = 0.94
Вікова категорія 0-4 роки: коефіцієнт = 1.06
Вікова категорія 35-39 років: коефіцієнт = 0.75
Вікова категорія 85 років і старші: коефіцієнт = 0.29
Вікова категорія 30-34 роки: коефіцієнт = 0.68
Вікова категорія 25-29 років: коефіцієнт = 0.71
Вікова категорія 20-24 роки: коефіцієнт = 0.83
Вікова категорія 70-74 роки: коефіцієнт = 0.56
Вікова категорія 15-19 років: коефіцієнт = 0.91
Вікова категорія 65-69 років: коефіцієнт = 0.71
Вікова категорія 55-59 років: коефіцієнт = 0.79
Вікова категорія 60-64 роки: коефіцієнт = 0.86
Вікова категорія 50-54 роки: коефіцієнт = 0.92